% Autogenerated data file from JSON file: 'data/auto_gen.json'

fields(4). % count fields

% subject(Semester, HT, HP, DT, DP, Field).
subject(1,  3,  8, 3, 2,  3). % Subject_0
subject(2,  0,  8, 1, 1,  3). % Subject_1
subject(2,  4,  6, 4, 1,  1). % Subject_2
subject(1,  0,  6, 2, 2,  1). % Subject_3

% teacherType(Type, AverageWeekHours).
teacherType(1,  7).
teacherType(2,  8).
teacherType(3,  9).

% teacher(Type, diff, Field).
teacher(3,  1, 3). % Teacher_0 - Jose Eilerman
teacher(1,  2, 1). % Teacher_1 - Alan Price
teacher(2, -3, 1). % Teacher_2 - Mary Tyson
teacher(2, -1, 3). % Teacher_3 - Joshua Robertson
