% Autogenerated data file from JSON file: 'data/auto_gen.json'

fields(1). % count fields

% subject(Semester, HT, HP, DT, DP, Field).
subject(1,  2, 18, 2, 2,  1). % Subject_0
subject(2,  6, 14, 3, 14,  1). % Subject_1
subject(2,  2,  5, 2, 1,  1). % Subject_2
subject(1,  0,  7, 1, 7,  1). % Subject_3
subject(1,  3, 15, 1, 3,  1). % Subject_4
subject(2,  3, 15, 1, 3,  1). % Subject_5

% teacherType(Type, AverageWeekHours).
teacherType(1,  7).
teacherType(2,  8).
teacherType(3,  9).

% teacher(Type, diff, Field).
teacher(1,  0, 1). % Teacher_0 - Vida Leone
teacher(3,  0, 1). % Teacher_1 - Anthony Kelley
teacher(1,  0, 1). % Teacher_2 - Linda Pauls
teacher(3,  0, 1). % Teacher_3 - Melanie Milne
teacher(3,  0, 1). % Teacher_4 - Katherine Rautio
teacher(2,  0, 1). % Teacher_5 - Kelly Mcknight
teacher(3,  0, 1). % Teacher_6 - Joan Black
