% Autogenerated data file from JSON file: '.\data\auto_gen_13.json'

fields(1). % count fields

% subject(Semester,  HT,  HP,  DT,  DP,  Field).
subject(1,  4, 18, 1, 2,  1). % Subject_0
subject(2,  0, 22, 0, 2,  1). % Subject_1
subject(2,  3, 18, 1, 2,  1). % Subject_2
subject(1,  0, 21, 0, 1,  1). % Subject_3
subject(1,  2, 12, 2, 2,  1). % Subject_4
subject(2,  0, 14, 0, 2,  1). % Subject_5
subject(2,  4,  6, 1, 2,  1). % Subject_6
subject(1,  0, 10, 0, 2,  1). % Subject_7
subject(1,  4, 12, 4, 3,  1). % Subject_8
subject(2,  0, 16, 0, 2,  1). % Subject_9
subject(2,  2, 18, 2, 2,  1). % Subject_10
subject(1,  0, 20, 0, 2,  1). % Subject_11
subject(1,  3, 16, 1, 2,  1). % Subject_12
subject(2,  0, 19, 0, 1,  1). % Subject_13
subject(2,  2, 14, 1, 2,  1). % Subject_14
subject(1,  0, 16, 0, 2,  1). % Subject_15
subject(1,  2, 14, 2, 2,  1). % Subject_16
subject(2,  0, 16, 0, 2,  1). % Subject_17
subject(2,  3, 12, 1, 3,  1). % Subject_18
subject(1,  0, 15, 0, 1,  1). % Subject_19
subject(1,  3,  6, 3, 2,  1). % Subject_20
subject(2,  0,  9, 0, 1,  1). % Subject_21
subject(2,  3, 12, 3, 3,  1). % Subject_22
subject(1,  0, 15, 0, 1,  1). % Subject_23
subject(1,  4, 16, 2, 2,  1). % Subject_24
subject(2,  0, 20, 0, 2,  1). % Subject_25

% teacherType(Type, AverageWeekHours).
teacherType(1,  7).
teacherType(2,  8).
teacherType(3,  9).

% teacher(Type, diff, Field).
teacher(3,  0, 1). %  8 -  8 Teacher_0 - Denise Gunn
teacher(2,  0, 1). %  8 -  8 Teacher_1 - Alex Briseno
teacher(1,  0, 1). %  6 -  6 Teacher_2 - Frances Begay
teacher(3,  0, 1). %  9 -  9 Teacher_3 - Terry Rehfield
teacher(1,  0, 1). %  6 -  6 Teacher_4 - Dean Douglas
teacher(3,  0, 1). %  6 -  6 Teacher_5 - Wm Lee
teacher(3,  0, 1). %  8 -  8 Teacher_6 - Jose Hartt
teacher(1,  0, 1). %  6 -  6 Teacher_7 - Charlene Frank
teacher(2,  0, 1). %  8 -  8 Teacher_8 - James Townsend
teacher(1,  0, 1). %  2 -  2 Teacher_9 - Ryan Farness
teacher(1,  0, 1). %  7 -  7 Teacher_10 - Joshua Montez
teacher(3,  0, 1). %  9 -  9 Teacher_11 - Barbara Schultz
teacher(1,  0, 1). %  6 -  6 Teacher_12 - Brandon Bearfield
teacher(2,  0, 1). %  8 -  8 Teacher_13 - Cynthia Ortega
teacher(3,  0, 1). %  6 -  6 Teacher_14 - Jennifer Sanders
teacher(1,  0, 1). %  7 -  7 Teacher_15 - Sharon Morris
teacher(2,  0, 1). %  8 -  8 Teacher_16 - Cora Wallner
teacher(2,  0, 1). %  4 -  4 Teacher_17 - Victor Barry
teacher(2,  0, 1). %  8 -  8 Teacher_18 - Joseph Snow
teacher(3,  0, 1). %  8 -  8 Teacher_19 - Leon Bullock
teacher(1,  0, 1). %  6 -  6 Teacher_20 - Stephanie Day
teacher(2,  0, 1). %  8 -  8 Teacher_21 - Diane Hull
teacher(3,  0, 1). %  2 -  2 Teacher_22 - Coleman Szabo
teacher(1,  0, 1). %  6 -  6 Teacher_23 - Judith Galbreath
teacher(2,  0, 1). %  6 -  6 Teacher_24 - Jordan Cruz
teacher(3,  0, 1). %  3 -  3 Teacher_25 - Byron Simpson
teacher(1,  0, 1). %  7 -  7 Teacher_26 - Sylvia Garza
teacher(3,  0, 1). %  2 -  2 Teacher_27 - Cara Taylor
teacher(1,  0, 1). %  6 -  6 Teacher_28 - Daniel Todd
teacher(2,  0, 1). %  6 -  6 Teacher_29 - Gladys Rankin
teacher(3,  0, 1). %  3 -  3 Teacher_30 - Dorothy Higgins
teacher(3,  0, 1). %  8 -  8 Teacher_31 - Bruce Blackston
teacher(1,  0, 1). %  6 -  6 Teacher_32 - Crystal Hubbard
teacher(2,  0, 1). %  6 -  6 Teacher_33 - Linda Graves
