% Autogenerated data file from JSON file: '.\data\medium.json'

fields(3). % count fields

% subject(Semester,  HT,  HP,  DT,  DP,  Field).
subject(1,  2, 18, 2, 3,  2). % Subject_0
subject(2,  0, 15, 0, 1,  2). % Subject_1
subject(2,  2, 16, 1, 2,  2). % Subject_2
subject(1,  0, 15, 0, 1,  2). % Subject_3
subject(1,  4, 18, 1, 3,  1). % Subject_4
subject(2,  0, 19, 0, 1,  1). % Subject_5
subject(2,  2, 12, 1, 3,  3). % Subject_6
subject(1,  0, 13, 0, 1,  3). % Subject_7

% teacherType(Type, AverageWeekHours).
teacherType(1,  7).
teacherType(2,  8).
teacherType(3,  9).

% teacher(Type, diff, Field).
teacher(2,  2, 2). %  8 -  6 Teacher_0 - Julia Ward
teacher(3,  1, 2). %  9 -  8 Teacher_1 - Russel Ricker
teacher(3,  2, 1). %  3 -  1 Teacher_2 - Mary Grim
teacher(2, -1, 2). %  7 -  8 Teacher_3 - Mona Britt
teacher(3, -2, 1). %  8 - 10 Teacher_4 - Donna Pasey
teacher(2,  2, 1). %  7 -  5 Teacher_5 - Robert Seymour
teacher(3,  1, 1). %  9 -  8 Teacher_6 - Curtis Bruley
teacher(2,  0, 2). %  6 -  6 Teacher_7 - Connie Gipson
teacher(3,  0, 3). %  8 -  8 Teacher_8 - Michael Hetz
teacher(1, -1, 1). %  5 -  6 Teacher_9 - Alicia Collins
