% Autogenerated data file from JSON file: '.\manual_data\simple.json'

fields(1). % count fields

% subject(Semester,  HT,  HP,  DT,  DP,  Field).
subject(1,  4, 10, 2, 5,  1). % Plog
subject(2,  4, 10, 2, 5,  1). % Plog Avançado

% teacherType(Type, AverageWeekHours).
teacherType(1,  7).
teacherType(2,  8).
teacherType(3,  9).

% teacher(Type, diff, Field).
teacher(1,  0, 1). %  _ -  _ Álvaro Alves
teacher(1,  0, 1). %  _ -  _ Bernardo Belo
